<?php

namespace App\Http\Middleware;

use Illuminate\Routing\Middleware\ValidateSignature as Middleware;

/**
 * The ValidateSignature middleware verifies signed URLs.
 * 
 * This middleware validates that a URL signature is valid. It is used to verify
 * that URLs with sensitive operations (like password resets, email verifications)
 * have not been tampered with and were generated by the application.
 */
class ValidateSignature extends Middleware
{
    /**
     * The names of the query string parameters that should be ignored.
     *
     * @var array<int, string>
     */
    protected $except = [
        // 'fbclid',
        // 'utm_campaign',
        // 'utm_content',
        // 'utm_medium',
        // 'utm_source',
        // 'utm_term',
    ];
}
